###############################################################################
#
#
#
###############################################################################
homeassistant:
  customize:

###############################################################################
#
# renaming / hiding entities
#
###############################################################################


    sensor.ring_backyard_last_ding:
      hidden: true
###############################################################################
#
# groups
#
###############################################################################
group:

  Ring_Doorbell:
    name: Ring Security Systems
    entities:
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - sensor.ring_front_door_battery
      - sensor.ring_front_door_volume
      - sensor.ring_front_door_wifi_signal_category
      - sensor.ring_front_door_wifi_signal_strength
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_motion
      - sensor.ring_front_door_last_activity
      - binary_sensor.ring_backyard_ding
      - binary_sensor.ring_backyard_motion
      - sensor.ring_backyard_battery
      - sensor.ring_backyard_volume
      - sensor.ring_backyard_last_motion
      - sensor.ring_backyard_last_activity
      - sensor.ring_backyard_wifi_signal_category
      - sensor.ring_backyard_wifi_signal_strength
      - binary_sensor.ring_pathway_ding
      - binary_sensor.ring_pathway_motion
      - sensor.ring_pathway_battery
      - sensor.ring_pathway_volume
      - sensor.ring_pathway_last_motion
      - sensor.ring_pathway_last_activity
      - sensor.ring_pathway_wifi_signal_category
      - sensor.ring_pathway_wifi_signal_strength
      - sensor.ring_hallway_volume
      - sensor.ring_hallway_wifi_signal_category
      - sensor.ring_hallway_wifi_signal_strength
      - camera.front_door
      - camera.pathway
      - camera.backyard



ring:
  username: !secret ring_username
  password: !secret ring_password

sensor:
  - platform: ring
    scan_interval: 120
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume
      - wifi_signal_category
      - wifi_signal_strength

binary_sensor:
  - platform: ring
    scan_interval: 120
    monitored_conditions:
      - ding
      - motion

camera:
  - platform: ring
    scan_interval: 120
### removed
#ffmpeg:
#  ffmpeg_bin: /usr/bin/ffmpeg
