group:
  yahoo:
    name: Yahoo Weather Conditions
    entities:
      - sensor.yweather_current
      - sensor.yweather_condition
      - sensor.yweather_temperature
      - sensor.yweather_temperature_max
      - sensor.yweather_temperature_min
      - sensor.yweather_wind_speed
      - sensor.yweather_visibility
      - sensor.yweather_humidity
      - sensor.yweather_pressure

sensor:
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature