###############################################################################
#
# Zwave Smart Outlets
#
###############################################################################
homeassistant:
#  customize:

group:
###############################################################################
# Groups  
############################################################################### 

  hot_tub_outlet:
    name: Hot Tub Outlet
    entities:
      - switch.hot_tub_outlet
      - sensor.hot_tub_outlet_consumption
      - sensor.hot_tub_outlet_usage
      - sensor.hot_tub_outlet_voltage_2

  office_monitor_outlet:
    name: Office Monitor Outlet
    entities:
      - switch.office_monitor_outlet
      - sensor.office_monitor_outlet_consumption
      - sensor.office_monitor_outlet_usage


  internet_outlet:
    name: Internet Outlet
    entities:
#      - sensor.internet
      - switch.internet_outlet
      - sensor.internet_outlet_consumption
      - sensor.internet_outlet_usage

  bedroom_outlets:
    name: Bedroom Outlets
    entities:
      - switch.bedroom_tv_outlet
      - sensor.bedroom_tv_outlet_consumption
      - sensor.bedroom_tv_outlet_usage

  living_outlets:
    name: Livingroom Outlets
    entities:
      - switch.livingroom_tv_outlet
      - sensor.livingroom_tv_outlet_consumption
      - sensor.livingroom_tv_outlet_usage
